from django.urls import path
from . import views

urlpatterns = [
    path('', views.apiOverview, name="api_overview"),
    path('teacher_list/', views.teacherList, name="teacher-list"),
    path('add_teacher/', views.addTeacher, name="add-teacher"),
    path('edit_teacher/<str:pk>/', views.editTeacher, name="edit-teacher"),
    path('delete_teacher/<str:pk>/', views.deleteTeacher, name="delete-teacher"),
    path('department_list/', views.departmentList, name="department-list"),
    path('add_department/', views.addDepartment, name="add-department"),
    path('add_timetable/', views.addTimetable, name="add-timetable"),
    path('edit_department/<str:pk>/', views.editDepartment, name="edit-department"),
    path('delete_department/<str:pk>/', views.deleteDepartment, name="delete-department"),
    path('course_list/', views.courseList, name="course-list"),
    path('add_course/', views.addCourse, name="add-course"),
    path('edit_course/<str:pk>/', views.editCourse, name="edit-course"),
    path('delete_course/<str:pk>/', views.deleteCourse, name="delete-course"),
    path('section_list/', views.sectionList, name="section-list"),
    path('add_section/', views.addSection, name="add-section"),
    path('edit_section/<str:pk>/', views.editSection, name="edit-section"),
    path('delete_section/<str:pk>/', views.deleteSection, name="delete-section"),
    path('room_list/', views.roomList, name="room-list"),
    path('add_room/', views.addRoom, name="add-room"),
    path('edit_room/<str:pk>/', views.editRoom, name="edit-room"),
    path('delete_room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('timeslot_list/', views.timeslotList, name="timeslot-list"),
    path('add_timeslot/', views.addTimeslot, name="add-timeslot"),
    path('edit_timeslot/<str:pk>/', views.editTimeslot, name="edit-timeslot"),
    path('delete_timeslot/<str:pk>/', views.deleteTimeslot, name="delete-timeslot"),
    path('timetable_list/', views.timetableList, name="timetable-list"),
    path('add_timetable', views.addTimetable, name="add=timetable"),
    path('generate_classes/<str:pk>', views.generateClasses, name="generate-timetable"),
    path('get_timetable/<str:pk>', views.getTimetable, name="get-timetable"),
    path('delete_timetable/<str:pk>', views.deleteTimetable, name="delete-timetable"),
]