# Generated by Django 3.0.8 on 2020-07-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('timing', 'day')},
        ),
    ]
