# Generated by Django 3.0.8 on 2020-07-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_api', '0002_auto_20200717_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='timeslots',
            new_name='timeslot',
        ),
    ]
