# Generated by Django 3.0.8 on 2020-07-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_api', '0004_auto_20200717_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler_api.Department'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler_api.Department'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler_api.Department')),
            ],
        ),
    ]
