# Generated by Django 3.0.8 on 2020-07-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_api', '0005_auto_20200717_2119'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('timing', 'day', 'department')},
        ),
    ]
