# Generated by Django 3.0.8 on 2020-07-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_api', '0006_auto_20200717_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['department']},
        ),
    ]
