# Generated by Django 3.0.8 on 2020-07-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_api', '0007_auto_20200717_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['department', 'day', 'timing']},
        ),
    ]
