# Generated by Django 3.0.8 on 2020-07-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_api', '0009_auto_20200717_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='department',
        ),
        migrations.AddField(
            model_name='class',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler_api.Timetable'),
        ),
    ]
