# Generated by Django 3.0.8 on 2020-07-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_api', '0010_auto_20200717_2203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('name', 'department')},
        ),
    ]
