# Generated by Django 3.0.8 on 2020-07-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_api', '0011_auto_20200717_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='timetable',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
